# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DockerCompose@0
  displayName: Run services
  inputs:
    dockerComposeFile: 'docker-compose.yml'
    action: 'Run services'
    detached: true
- script: |
    docker exec -ti vuejs-fronedn npm run test:unit
  displayName: 'Client tests: Run unit tests'
- script: |
    docker exec -ti vuejs-fronedn npm run test:e2e
  displayName: 'Client tests: Run e2e tests'