version: '3.6'
services:

  # client:
  #   build:
  #     context: ./client
  #   environment:
  #     client_PORT: 8080
  #     API_HOST: 'http://localhost:8080'
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./client/src:/app/src/
  #   links:
  #     - server


  server:
    build:
      context: ./server/
    expose:
      - 3000
    environment:
      API_HOST: 'http://localhost:3000'
      APP_SERVER_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/srv/app/server/src
    command: npm start
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: 'termino_database'
    volumes:
      - mongodata:/data/db
      - mongodb_config:/data/configdb
      - ./mongodb/:/docker-entrypoint-initdb.d/
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    command: mongod

# Create volume for mongodb data because volume mounting is not working for windows machines
volumes:
  mongodata:
  mongodb_config: