version: '3.6'
services:

  client:
    container_name: vuejs-frontend
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    environment:
      client_PORT: 8080
      API_HOST: 'http://localhost:8080'
    ports:
      - 8080:8080
    volumes:
      - ./client/src:/app/src/
    links:
      - server


  server:
    container_name: nestjs-backend
    build:
      context: ./server/
    expose:
      - 3000
    environment:
      API_HOST: 'http://localhost:3000'
      APP_SERVER_PORT: 3000
    ports:
      - 3000:3000
    volumes:
      - ./server/src:/app/src/
    command: npm run start:dev
    depends_on:
      - mongodb

  mongodb:
    container_name: mongo-database
    image: mongo:latest
    container_name: 'skeleton_database'
    volumes:
      - mongodata:/data/db
      - mongodb_config:/data/configdb
      - ./mongodb/:/docker-entrypoint-initdb.d/
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    command: mongod

# Create volume for mongodb data because volume mounting is not working for windows machines
volumes:
  mongodata:
  mongodb_config: